name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm install
          npm install --prefix server
          npm install --prefix client
      
      - name: Build client
        run: npm run build --prefix client
      
      - name: Deploy to Vercel
        uses: vercel/action@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          AI_SERVICE_URL: ${{ secrets.AI_SERVICE_URL }}
          NODE_ENV: production
      
      - name: Verify deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Check your Vercel dashboard for deployment details"

